### ISSUE TITLE
Problem with os.clock and schedulers

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1717]
Hey,

I wanted to measure the time of how long the code needs and tried to use os.clock. It looks like that os.clock and schedulers aren't working together nicely.

I created for quicker testing a scheduler that runs 5s later
```
Before starting: 15.744292
-- run scheduler 5s later
Written from scheduler: 15.863173
```

How you see, there is a small problem with them.

**Comment by worktycho** [comment]
What was the call to ScheduleTask? It takes the time to wait in Ticks, which is ~1/20 of a second.

**Comment by Seadragon91** [comment]
Sorry, the 5s are the time to wait - 100 ticks.

**Comment by madmaxoft** [comment]
As @worktycho already said - **show us your code**

**Comment by Seadragon91** [comment]
Here is the code
```
function Initialize(Plugin)
    Plugin:SetName("TestPlugin")
    Plugin:SetVersion(1)
    
    PLUGIN = Plugin
    
    -- Command Bindings
    cPluginManager.BindCommand("/test", "test", CmdTest , " test")
    
    LOG("Initialised " .. Plugin:GetName() .. " v." .. Plugin:GetVersion())
    return true
end


function CmdTest(a_Split, a_Player)
    START = os.clock()
    
    local CALLBACK = 
            function(a_World)
                a_Player:SendMessageInfo("start = " .. START)
                a_Player:SendMessageInfo("current = " .. os.clock())
            end
    
    a_Player:GetWorld():ScheduleTask(100, CALLBACK) -- run task in 5s
    a_Player:SendMessageInfo("Running...")
    return true
end

```

**Comment by madmaxoft** [comment]
I have tested similar code (in the Debuggers plugin: https://github.com/mc-server/MCServer/blob/master/MCServer/Plugins/Debuggers/Debuggers.lua#L1609-L1620 ) and it works alright for me.

But then I remembered that `clock()` behaves differently on Windows (my tests) and on Linux (Your tests?) - on Windows it returns the wall time elapsed since program start, while on Linux it returns the amount of time that the program has spent actively using the CPU since its start. This means that you should not use `os.clock()` for timing purposes, you should use `os.time` instead.

If you change your code to work on a console command and log its output to the console, you should be able that the log line timestamps are the specified time apart. Or just test the Debuggers plugin's `sched` console command.

**Comment by madmaxoft** [comment]
http://www.lua.org/pil/22.1.html
