### ISSUE TITLE
Cannot craft Polished Granite, Diorite, or Andisite

### ISSUE THREAD

**Issue by carc1n0gen** [mc-server/MCServer#1774]
When crafting these blocks they either immediately turn in to Stone Bricks or they do at a later time when viewing my inventory.

**Comment by Raekye** [comment]
I'll try this on the weekend if no-one else has fixed it by then

**Comment by NiLSPACE** [comment]
You can use my [CraftMaker](https://github.com/NiLSPACE/CraftMaker) plugin to create new recipes really easy.

**Comment by Raekye** [comment]
So I've been tracing the recipes - dumping out values, it seems like the recipe is fine, but the server doesn't have the right items in the user's crafting grid (thinks it's plain stone, instead of having the right meta/block damage):

```
[5952816b0cd4cd54|17:37:26] Recipe ingredients:
[5952816b0cd4cd54|17:37:26] Slot (0, 0): Type 1, health 0, count 1
[5952816b0cd4cd54|17:37:26] Slot (1, 0): Type 1, health 0, count 1
[5952816b0cd4cd54|17:37:26] Slot (0, 1): Type 1, health 0, count 1
[5952816b0cd4cd54|17:37:26] Slot (1, 1): Type 1, health 0, count 1
```

Also, other related recipes seem broken too, e.g. diorite + cobblestone -> andesite

Just thought I'd share my (basic) findings, I'll get back to when I can hopefully soon, if no-one's fixed it by then

**Comment by jammet** [comment]
Is this going to be corrected at some point? And what can I do with CraftMaker to fix it in the meantime? I can't "replace" receipes that're already there, or can I?

**Comment by madmaxoft** [comment]
@Raekye It's not exactly that the server has bad items, the server matched the wrong recipe.

Normally when matching recipes, an item health of zero is interpreted as "any item health can match". This is so that beds and paintings can be crafted out of any kind of wool (and there are possibly other examples of when this is needed) Therefore when the server comes across the recipe
```
StoneBrick, 4           = Stone,     1:1, 1:2, 2:1, 2:2
```
it matches it to the contents of the crafting grid, even though one would expect it to match the line
```
PolishedGranite, 4      = Granite, 1:1, 1:2, 2:1, 2:2
```
that comes 5 lines below.

Even worse, when you put stacks of granite into the crafting grid and craft the resulting stone bricks, the server will convert the rest of your granite stacks into plain stone.

**Comment by madmaxoft** [comment]
Moving the `PolishedGranite` line up above the `StoneBrick` line completely fixes the problem.
