### ISSUE TITLE
Somewhat inefficient continuous integration?

### ISSUE THREAD

**Issue by tigerw** [mc-server/MCServer#1795]
Currently builds run for pull requests and a simulation of a merge of that into master (?).

----

Travis does all of these:

1. Release, x64, GCC
2. Debug, x64, GCC
3. Release, x86, GCC
4. Debug, x86, GCC
5. Release, x64, Clang
6. Debug, x64, Clang
7. Release, x86, Clang
8. Debug, x86, Clang
9. Coverage, GCC

twice (pr and push).

----

Suggestions:

* Clang's always more picky, so there's no need to test GCC separately if it works on the former.
* If it works for 64 bit, it's unlikely not to work for 32.
* What does the coverage build do?
* What does the `uploadCoverage.sh` script do? An excerpt from its output:
```sh
StringUtils.cpp.gcno:version '408*', prefer '406*'
Segmentation fault
TCPLinkImpl.cpp.gcno:version '408*', prefer '406*'
Segmentation fault
ServerHandleImpl.cpp.gcno:version '408*', prefer '406*'
Segmentation fault
```

----

Suggested remedy:

1. Release, x64, Clang
2. Debug, x64, Clang
3. Coverage, GCC

**Comment by bearbin** [comment]
I don't believe that there's a problem, the current builds run fine, even if they are inefficient. I don't mind what you do as long as CI still works :P

**Comment by tigerw** [comment]
If nobody minds about slower builds then there's no need to change anything.

Still, question for @worktycho about uploadCoverage.sh

**Comment by worktycho** [comment]
upload coverage does a build with text coverage against the unit tests that are done as part of a build then uploads the results to coveralls.io. I would've add the results to the read-me but they were too terrible (~0.7%) Looks like that's broken now though.

**Comment by madmaxoft** [comment]
I do mind that a single CI build takes over 40 minutes, that's just too long. I wouldn't mind having only those 3 @tigerw suggested.

Also I expect that if we ever switch to using libraries present at the system, instead of compiling them on our own (where available), it should cut the build time, too.

**Comment by SphinxC0re** [comment]
![auswahl_005](https://cloud.githubusercontent.com/assets/3702016/6587480/0e3400ee-c785-11e4-8c25-16e46ecb599f.png)
Just saying...
And sometimes the 64bit builds work, but the 32bit builds do not.

**Comment by worktycho** [comment]
That's the gcc builds, not 64 bit builds. 64 bit builds are 3,4,7 and 8 on that list. Also that was at the time when we had not yet depreciated gcc 4.3 which only had partial c++11 support. So it was essential to test under gcc to ensure that the features we were using were supported. Now we use gcc 4.8 which has a complete c++11 support so that's not so much of an issue. VS2013 which we don't do CI builds against is far more of an issue now.

**Comment by madmaxoft** [comment]
We did have a MSVC2013 CI build, but it got messy because GitHub didn't support multiple CIs at that time. Now it is disabled, I'll try reactivating it.
