### ISSUE TITLE
Doors can't be placed on top-half slabs

### ISSUE THREAD

**Issue by wraith11** [mc-server/MCServer#1849]
If a door is placed on a top-half slab only a client sided door appears.

**Comment by aligator** [comment]
In MCServer it only checks if the block is a complete block: (BlockDoor.h)
```
/** Returns true if door can be placed on the specified block type. */
static bool CanBeOn(BLOCKTYPE a_BlockType)
{
// Vanilla refuses to place doors on transparent blocks
// We need to keep the door compatible with itself, otherwise the top half drops while the bottom half stays
return !cBlockInfo::IsTransparent(a_BlockType) || IsDoorBlockType(a_BlockType);
}
```

In minecraft it checks if the top surface is solid. I don't know if this is hard to implement.


Another problem:
In vanilla, I cna't place a door on top of a door (with shift-click) in MCServer this is possible because of the code I posted above.

**Comment by madmaxoft** [comment]
There is already a pull request being reviewed that solves this issue. As for the second issue, I'd consider that a bug in vanilla and a feature of MCS.
