### ISSUE TITLE
MCServer crash help command

### ISSUE THREAD

**Issue by LO1ZB** [mc-server/MCServer#2017]
MCServer crashed while executing core's 'help' command
stacktrace:
http://pastebin.com/Ft50RTab

**Comment by madmaxoft** [comment]
This is the new API check I enabled in debug builds in Lua. So we do use Lua wrongly.

**Comment by madmaxoft** [comment]
The crash doesn't happen to me on neither Windows nor Linux, there had to be something more going on. Did you have a plugin that reported an error? Or an error report while executing another command?

**Comment by LO1ZB** [comment]
Did you cleand the project befor (re) compiling in debug mode? Otherwise lua wount be (re) compiled in debug mode.

**Comment by madmaxoft** [comment]
I only have debug mode builds.

Wait, did you mean the console command, or the in-game command?

**Comment by madmaxoft** [comment]
Oh, the in-game command does indeed trigger the assert. I'll fix that.

**Comment by madmaxoft** [comment]
This might be deeper than I initially thought.

The callbacks aren't called properly, they forgot to pop the return value off from the Lua stack, so each call to the callback increased the stack until it grew over the default limit (20 items). Lua allows a function to have more items on the stack, but it needs to ask explicitly, and in this case we don't want to ask, because this is clearly an error. The question is, how many other places like this are there.

I'll refactor the `ForEachCommand()` wrapper function to use the stack properly, but I'm afraid we might run into this again somewhere else.

**Comment by SafwatHalaby** [comment]
I'm not following closely right now, so I'll ask:
Is this relevant to testing?

**Comment by madmaxoft** [comment]
It fixes a possible memory leak and crash, so I guess it's relevant enough.
