### ISSUE TITLE
"Webserver vs world threads" question

### ISSUE THREAD

**Issue by tigerw** [mc-server/MCServer#2137]
> Suppose that two admins are in, one is using the webadmin and the other is in-game. Both try to kick a player at the same time. The webadmin locks the plugin, so that it can execute the plugin code, but right at this moment the OS switches threads. The world thread locks the world so that it can access the list of in-game commands, receives the in-game command, it tries to lock the plugin. The plugin is already locked, so the world thread is put on hold. After a while, the webadmin thread is woken up again and continues processing. It tries to lock the world so that it can traverse the playerlist, but the lock is already held by the world thread. Now both threads are holding one lock each and trying to grab the other lock, and are therefore deadlocked.

I cannot seem to find the place where the world is locked by the admin in-game. It goes like `Protocol::HandleChatPacket` > `ClientHandle::HandleChat` > `Server::Command` > `PluginManager::CallHookChat` > `PluginManager::HandleCommand` > `PluginLua::HandleCommand` (PluginLua mutex locked). This means that if the webadmin has the plugin's lock, a command in-game won't deadlock if there is a thread switch, since it doesn't lock the world before the plugin. Have I overlooked something?

**Comment by madmaxoft** [comment]
I suppose this particular example is no longer valid. Let me give you another one:

Thread A is executing a world tick, it has the world's mutex locked for that reason, and the OS switches threads.
Thread B is executed, it receives a webadmin request and starts generating the webadmin page - it locks the plugin mutex to execute the Lua code, and because the plugin's webadmin handler has a `cWorld:ForEachPlayer()` call in it, tries to lock the world's mutex to enumerate the players. The thread is paused because the mutex is currently held by thread A.
Thread A is resumed. It detects that an entity is being attacked, and tries to call the `OnTakeDamage` hook implemented in the same plugin. It tries to lock the plugin's mutex, but is paused because it is already held by thread B. Deadlock.

**Comment by tigerw** [comment]
I see. How about use something like `std::lock`? The webadmin could obtain the plugin and the world mutexes, and pass those to std::lock, which either locks both, or none if one is already locked, blocking until available. So, the webadmin won't hold the plugin's lock when the world is busy, allowing the world to finish processing and release its mutex, whence the webadmin takes over.

Would that work?

**Comment by worktycho** [comment]
The problem is that doing that leaks the abstraction, as the fact that the plugin is going to obtain the world lock is not known ahead of time, so you need to either hold the world lock for plugins that don't need it, (inefficient) or interrupt the plugin, which has issues discussed in http://forum.mc-server.org/showthread.php?tid=1899

**Comment by tigerw** [comment]
Confound. Is there really no way to avoid deadlocks without all of those queues and delayed-execution functions?

**Comment by worktycho** [comment]
The other option discussed was keeping the web output open, and then allowing the plugin to schedule code on the tick thread which then sends the response. This is non-optimal for latency reasons, but would be simplest for plugin authors.

One thing that wasn't discussed but I just thought of was to add the ability to hold on to the web output, and then adding a callback function ScheduleTaskWithWorld to the web object, which would schedule the plugin code to be executed on the web thread immediately, but would cause the wrapper code to gain the world lock before gaining the plugin lock. There would also need to be a corresponding ScheduleTask, which could be used to exit back out of the world lock.

**Comment by tigerw** [comment]
Hm. Okay, thanks!
